FROM praqma/network-multitool
RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base
RUN mkdir /rx
WORKDIR /rx
COPY . /rx
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD [ "rx.py" ]