FROM ubuntu:18.04

RUN \
      apt-get update && apt-get install --no-install-recommends -y \
      git \
      cmake \
      build-essential \
      vim \
      libssh-dev \
      libssl-dev \
      openssh-server \
      python \
      python-pip \
      python-setuptools \
      net-tools \
      iputils-ping

RUN mkdir /app
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]